# See. https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/f9352f922501aea9ae0f626bf15b6a24ac72b2f9/cloudbuild.tmpl.yaml
logsBucket: gs://cloudbuildlog-2x
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        echo "docker image tag test is :: $$DOCKER_IMAGE_TAG"
        echo "docker image tag test2 is :: $${DOCKER_IMAGE_TAG}"
        echo $$DOCKER_IMAGE_TAG
        echo $IMAGE_TAG_TEST
        echo $$IMAGE_TAG_TEST
        echo "docker image tag test3 is :: ${DOCKER_IMAGE_TAG}"
        echo "docker image tag test4 is :: $DOCKER_IMAGE_TAG"
    env:
      - IMAGE_TAG_TEST=test_$_BUILD_SHA

  - id: build-python
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=us.gcr.io/$PROJECT_ID/linebot/python:$IMAGE_TAG_TEST
      - --cache=true
      - --cache-ttl=336h
      - --dockerfile=deployment/dockerfile/python/Dockerfile
      - --context=.
    env:
      - IMAGE_TAG_TEST=test_$_BUILD_SHA

  - id: build-go
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=us.gcr.io/$PROJECT_ID/linebot/go:${TAG2}
      - --cache=true
      - --cache-ttl=336h
      - --dockerfile=deployment/dockerfile/go/Dockerfile
      - --context=.
    env:
      - TAG2=test_$_BUILD_SHA

  - id: Deploy To Cloud Run
    waitFor:
      - build-python
      - build-go
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $$SERVICE_NAME
      - --image
      - us.gcr.io/$PROJECT_ID/linebot/python:$$TAG
      - --region
      - $REGION
      - --platform
      - managed
    env:
      - SERVICE_NAME=mintaklinebot

images:
  - us.gcr.io/$PROJECT_ID/linebot/python
  - us.gcr.io/$PROJECT_ID/linebot/go

options:
  machineType: N1_HIGHCPU_32
  env:
    - REGION=us-west1
    - DOCKER_IMAGE_TAG=${_BRANCH}-${_BUILD_SHA}
    - SERVICE_NAME=mintaklinebot
    - KANIKO_CACHE_TTL=336h
