apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: linebot
  annotations:
    # 前提：Managed CertificateとSSL PolicyはあらかじめTerraformで作成済
    networking.gke.io/v1beta1.FrontendConfig: mintaklinebot-frontendconfig
    ingress.gcp.kubernetes.io/pre-shared-cert: mintaklinebot-managed-cert
    kubernetes.io/ingress.global-static-ip-name: mintaklinebot-external-ip
    kubernetes.io/ingress.allow-http: "false"
  labels:
    app: linebot
spec:
  backend:
    serviceName: linebot-backend
    servicePort: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: mintaklinebot-frontendconfig
spec:
  sslPolicy: mintaklinebot-ingress-ssl-policy
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: linebot-backendconfig
spec:
  healthCheck:
    type: HTTP
    requestPath: /health
  securityPolicy:
    name: mintaklinebot-security-policy
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
---
apiVersion: v1
kind: Service
metadata:
  name: linebot-backend
  labels:
    app: linebot
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"linebot-backendconfig"}}'
spec:
  type: ClusterIP
  selector:
    app: linebot
    tier: api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
