apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linebot-api
  namespace: default
spec:
  encryptedData:
    CHANNEL_ACCESS_TOKEN: AgByaa/GlH9czft7yNk2TAHT34XFJSCkcMn6c8sJO+s5T6zcE0fEi4d828sG7P33cc8srabhLyQa1NXXtGSDdh1uqmXxCP0T1xzTcvnOrZOMXrIGDnJJzw1ewZ3Pj/Mym7vfZe4yGFwWhJVbP4q7sGs7aaCj+Lor2MJ8iv3r8FVTXKsyMHe2uJxqDvGdvMTiy6vFwylzkMHUWog2aCWa2OQJ+ZCfs716cstlZA8WM75J4IypGqPfZXzzNDbk8P9Jf1XSaTkBslZfquAxNEkif5F/5MHLqvToX6MjhC2aZsheMThVg23utmMfI9PtQEdQMovYvdK8QEe43bmbXYRfnx/iNYRu6J8EOsnzJIXy3x2btNEe0oNkVl74lL3sVans+edIZox6EnYL/+2+vP7unsCwqBvdiewzZscP9tRJIjRmVk7DkINoQFdZ8T8ucEW5ELkwOa2inBLptP2DIsnrSuGCvZvVHaPae/9wUgKVzaV2i2Qk+F82w06dvhuQl6hgbGzK0jOPeCBbWpiUz6FbvC9oaPJdIU0j4mPEuXn0+3sT7Ci+ZvVfz9CjPTGqr4/0px38gTC/8p8E5U7ULN3J8hIfF4cJup/EWVdAaNBcIfX1DmmDrVc9FsGwkLINRE3s9qgGU4IOLwyHFs2emJFuDQfPHuCcVk9+EiRe3syo/TsJJ4rl320pmp0qGH3aUWpzlpwFVVo4IeCQQpj/4S4g/dKZnEvbXCiNtgmLaarcF1N5aiHl0YrdDJJK7E0mS8iP9O1nA/ykNMWSPK0WNz97aXOdwitVYb6Dp3gUdqLEsaE9zmsz+zge/FpJaxkLocpxU5hlAE/9pLVu9RbiUX1mjFoRvZQbrJ2n5fZmOkQOf72BpIVbWDgo8sEtNTASzxT5XoBZuFxAkfg5jr+JxVF207gKeZRnNhT7jYR049fw
    CHANNEL_SECRET: AgAaOp1iSzzzrQ77nt83zp4id7KgZV5vBesFuwBAeKyqtjdtDKv3YVeBrPlWYRulVvc0qNsG1t2FjrFfiODTzyD28mL0FCCBXk5qoAvcyKSqR4zjwhJZY0zopq7MfjhNH4+V2ToB+NWqRUDSoT6+VrJyeXlJi0UQVOZR48P48DmsWCp9sc3G5HeeyFgQ6e193gx24pi1/ufHJM769nPOcGMmjklV37EAsCbMzbBtKGLH2fNw7eUR14liu6+ytpezm+Li1TE9jHffxyaasuTuiGsFmSGyOCW9XtpqJSOnaSkyXYPGZUx9vbSF0XU+Xg4eX1WjcIoFqHfE9/GJGP8+f929aC/oeVAY+JHptbylvBf8+72Bo+wF3CPM/2iCLDVi9Up0P8lvAZ6vxhjVNVLm/qB7x5q8jNd5dcngJsA0aLZ15JIcxu1Gc2gGfgCzhH/erkvnQNrCLzK9BBF6p7y8JDJMfoqcMKwUZ8Pg7e+JeFA7v2e93q8xS2ooCf70jXxcv2iwRAMbPA2AgI+oxivhCGPCC54dML16gdx3ueVJBVhJC/IZHIYBA+OJRZqXQ/24EWiytSuDgyaOM64RebP4+aYCiLljiZ4DeK5p007y68uN90cDCtWkQjTNwGqz1+m9WvbsrJ7FiV/FRX5nILqA90Zs7REJ4OaHvgkC+7Xp+Wl2qmbdvh1g+FxkHYHV9/uqTIoPFvfLcRVTVSo91W6w7VzStxgNcW/zUyxIsOG6OdtW7Q==
  template:
    metadata:
      creationTimestamp: null
      name: linebot-api
      namespace: default

