name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master
      - cloudrun

env:
  GCLOUD_VERSION: 311.0.0
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-nodejs

jobs:
  build:
    name: Build And Push Container Registry
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Setup GCloud
        id: setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCLOUD_VERSION }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Cloud Build
        id: cloud-build
        run: |-
          gcloud builds submit --config cloudbuild.yml
  # deploy:
  #   name: Deploy to Cloud Run
  #   needs: [build]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Setup GCloud
  #       id: setup
  #       uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.1.3
  #       with:
  #         version: ${{ env.GCLOUD_VERSION }}
  #         service_account_key: ${{ secrets.RUN_SA_KEY }}
  #         project_id: ${{ secrets.RUN_PROJECT }}
  #     # Deploy image to Cloud Run
  #     - name: Deploy
  #       run: |-
  #         gcloud run deploy "$SERVICE_NAME" \
  #           --quiet \
  #           --region "$RUN_REGION" \
  #           --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
  #           --platform "managed" \
  #           --allow-unauthenticated
