name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  GCLOUD_VERSION: 311.0.0
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  terraform-apply:
    name: Create GCP Resources
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

  build-and-deploy:
    name: Build And Push Container Registry
    needs: [terraform-apply]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Get Version
        id: version
        run: |
          echo ::set-output name=source_branch::${GITHUB_REF#refs/heads/}

      - name: Setup GCloud
        id: setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCLOUD_VERSION }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Cloud Build
        id: cloud-build
        run: |-
          gcloud builds submit \
          --config cloudbuild.yml \
          --substitutions _DOCKER_IMAGE_TAG=${{ steps.version.outputs.source_branch }}-${{ github.sha }} \
          --gcs-source-staging-dir gs://mintak_cloudbuild/source
